import { FunctionComponent } from "react";
import SectionText from "./SectionText";
import ContentBox from "./ContentBox";

export type FeaturesType = {
  className?: string;
};

const Features: FunctionComponent<FeaturesType> = ({ className = "" }) => {
  return (
    <footer
      className={`self-stretch flex flex-row items-start justify-end py-0 pl-11 pr-9 box-border max-w-full mt-[-30px] text-center text-xl text-blue-gray-600 font-body-s mq450:pl-5 mq450:box-border ${className}`}
    >
      <div className="h-[1017px] flex-1 relative overflow-hidden max-w-full z-[2]">
        <SectionText
          headline2="Your favourite tools"
          headline2
          headline1
          text
          caption
          caption="Caption"
          buttons
          button3
          headline1="Headline One"
          button2
          text="In risus nec molestie at in pulvinar tellus. At integer id condimentum gravida nisi nisl. Sem vitae porttitor arcu congue sem erat et sit faucibus. Sollicitudin elit gravida tellus mattis porttitor."
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus2.svg"
          text2
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright1.svg"
          iconRight1={false}
          iconLeft1={false}
          propBackgroundColor2="#c026d3"
          propHeight2="64px"
          propFlex2="unset"
          propBorderRadius2="26px"
          propBorder1="2px solid #c026d3"
          propPadding2="20px 22px"
          propBoxShadow1="unset"
          propAlignSelf3="stretch"
          propColor2="#fff"
          propAlignSelf12="stretch"
          propFontSize2="24px"
          propFontWeight2="bold"
          propMargin2="unset"
          buttonMinWidth1="unset"
          textContainerHeight1="unset"
        />
        <ContentBox
          titleBadge={false}
          imageBadge={false}
          category={false}
          title="Sapien amet est"
          imageUnderTitle={false}
          category="Category"
          text="Viverra netus odio nunc ac nibh lorem iaculis. Orci facilisis habitasse cursus tempor et."
          image={false}
          title
          text
          imageThumb={false}
          author={false}
          icon
          buttons={false}
          titleIcon={false}
          propPosition="absolute"
          propTop="231px"
          propLeft="80px"
          propWidth="145.7px"
          picture="/picture4@2x.png"
          propWidth1="unset"
          propHeight="unset"
          propBorderRadius="unset"
          propBackgroundColor="unset"
          propPadding="unset"
          iconTablerIconsViewfinder="/icon--tablericons--mailfast.svg"
          propAlignSelf="unset"
          propAlignSelf1="unset"
          propMargin="0"
          propFontSize="20px"
          propFontWeight="700"
          propTextAlign="left"
          propFlex="unset"
          iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--pencil1.svg"
          picture1="/picture4@2x.png"
          propColor="#475569"
          propTextAlign1="left"
          userThumb="/user-thumb-4@2x.png"
          propLeft1="calc(50% - 47.85px)"
          contentBoxAlignSelf="unset"
          contentBoxFlex="unset"
          categoryAlignSelf="stretch"
          categoryWidth="unset"
          pictureIconAlignSelf="stretch"
          pictureIconOverflow="hidden"
          pictureIconWidth="unset"
          paragraphFontSize="12px"
          userCardAlignSelf="stretch"
          userCardWidth="unset"
          userCardFlexWrap="unset"
          buttonsGroupFlexWrap="unset"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus4.svg"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus5.svg"
          text2
          text2
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-12.svg"
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-13.svg"
          iconRight1
          iconRight1
          iconLeft1={false}
          iconLeft1={false}
          propBackgroundColor2="#2563eb"
          propBackgroundColor2="unset"
          propHeight2="48px"
          propHeight2="48px"
          propFlex2="1"
          propFlex2="1"
          propBorderRadius2="8px"
          propBorderRadius2="8px"
          propBorder1="2px solid #2563eb"
          propBorder1="2px solid #2563eb"
          propPadding2="12px 9px"
          propPadding2="12px 9px"
          propBoxShadow1="unset"
          propBoxShadow1="unset"
          propAlignSelf3="stretch"
          propAlignSelf3="stretch"
          propColor2="#fff"
          propColor2="#2563eb"
          propAlignSelf12="stretch"
          propAlignSelf12="stretch"
          propFontSize2="16px"
          propFontSize2="16px"
          propFontWeight2="500"
          propFontWeight2="500"
          propMargin2="unset"
          propMargin2="unset"
          buttonMinWidth="unset"
          buttonMinWidth1="unset"
          textContainerHeight="unset"
          textContainerHeight1="unset"
        />
        <ContentBox
          titleBadge={false}
          imageBadge={false}
          category={false}
          title="Tortor ornare"
          imageUnderTitle={false}
          category="Category"
          text="Nulla etiam mattis amet suspendisse lacus nulla sed urna ultricies. "
          image={false}
          title
          text
          imageThumb={false}
          author={false}
          icon
          buttons={false}
          titleIcon={false}
          propPosition="absolute"
          propTop="231px"
          propLeft="273.7px"
          propWidth="145.7px"
          picture="/picture5@2x.png"
          propWidth1="unset"
          propHeight="unset"
          propBorderRadius="unset"
          propBackgroundColor="unset"
          propPadding="unset"
          iconTablerIconsViewfinder="/icon--tablericons--map2.svg"
          propAlignSelf="stretch"
          propAlignSelf1="stretch"
          propMargin="0"
          propFontSize="20px"
          propFontWeight="700"
          propTextAlign="left"
          propFlex="1"
          iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--pencil1.svg"
          picture1="/picture5@2x.png"
          propColor="#475569"
          propTextAlign1="left"
          userThumb="/user-thumb-5@2x.png"
          propLeft1="calc(50% - 47.85px)"
          contentBoxAlignSelf="unset"
          contentBoxFlex="unset"
          categoryAlignSelf="stretch"
          categoryWidth="unset"
          pictureIconAlignSelf="stretch"
          pictureIconOverflow="hidden"
          pictureIconWidth="unset"
          paragraphFontSize="12px"
          userCardAlignSelf="stretch"
          userCardWidth="unset"
          userCardFlexWrap="unset"
          buttonsGroupFlexWrap="unset"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus4.svg"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus5.svg"
          text2
          text2
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-12.svg"
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-13.svg"
          iconRight1
          iconRight1
          iconLeft1={false}
          iconLeft1={false}
          propBackgroundColor2="#2563eb"
          propBackgroundColor2="unset"
          propHeight2="48px"
          propHeight2="48px"
          propFlex2="1"
          propFlex2="1"
          propBorderRadius2="8px"
          propBorderRadius2="8px"
          propBorder1="2px solid #2563eb"
          propBorder1="2px solid #2563eb"
          propPadding2="12px 9px"
          propPadding2="12px 9px"
          propBoxShadow1="unset"
          propBoxShadow1="unset"
          propAlignSelf3="stretch"
          propAlignSelf3="stretch"
          propColor2="#fff"
          propColor2="#2563eb"
          propAlignSelf12="stretch"
          propAlignSelf12="stretch"
          propFontSize2="16px"
          propFontSize2="16px"
          propFontWeight2="500"
          propFontWeight2="500"
          propMargin2="unset"
          propMargin2="unset"
          buttonMinWidth="unset"
          buttonMinWidth1="unset"
          textContainerHeight="unset"
          textContainerHeight1="unset"
        />
        <ContentBox
          titleBadge={false}
          imageBadge={false}
          category={false}
          title="Vel lacus"
          imageUnderTitle={false}
          category="Category"
          text="Porttitor quis lectus varius quis dolor morbi massa pellentesque."
          image={false}
          title
          text
          imageThumb={false}
          author={false}
          icon
          buttons={false}
          titleIcon={false}
          propPosition="absolute"
          propTop="231px"
          propLeft="467.3px"
          propWidth="145.7px"
          picture="/picture6@2x.png"
          propWidth1="unset"
          propHeight="unset"
          propBorderRadius="unset"
          propBackgroundColor="unset"
          propPadding="unset"
          iconTablerIconsViewfinder="/icon--tablericons--manualgearbox.svg"
          propAlignSelf="stretch"
          propAlignSelf1="stretch"
          propMargin="0"
          propFontSize="20px"
          propFontWeight="700"
          propTextAlign="left"
          propFlex="1"
          iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--pencil1.svg"
          picture1="/picture6@2x.png"
          propColor="#475569"
          propTextAlign1="left"
          userThumb="/user-thumb-2@2x.png"
          propLeft1="calc(50% - 47.85px)"
          contentBoxAlignSelf="unset"
          contentBoxFlex="unset"
          categoryAlignSelf="stretch"
          categoryWidth="unset"
          pictureIconAlignSelf="stretch"
          pictureIconOverflow="hidden"
          pictureIconWidth="unset"
          paragraphFontSize="12px"
          userCardAlignSelf="stretch"
          userCardWidth="unset"
          userCardFlexWrap="unset"
          buttonsGroupFlexWrap="unset"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus4.svg"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus5.svg"
          text2
          text2
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-12.svg"
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-13.svg"
          iconRight1
          iconRight1
          iconLeft1={false}
          iconLeft1={false}
          propBackgroundColor2="#2563eb"
          propBackgroundColor2="unset"
          propHeight2="48px"
          propHeight2="48px"
          propFlex2="1"
          propFlex2="1"
          propBorderRadius2="8px"
          propBorderRadius2="8px"
          propBorder1="2px solid #2563eb"
          propBorder1="2px solid #2563eb"
          propPadding2="12px 9px"
          propPadding2="12px 9px"
          propBoxShadow1="unset"
          propBoxShadow1="unset"
          propAlignSelf3="stretch"
          propAlignSelf3="stretch"
          propColor2="#fff"
          propColor2="#2563eb"
          propAlignSelf12="stretch"
          propAlignSelf12="stretch"
          propFontSize2="16px"
          propFontSize2="16px"
          propFontWeight2="500"
          propFontWeight2="500"
          propMargin2="unset"
          propMargin2="unset"
          buttonMinWidth="unset"
          buttonMinWidth1="unset"
          textContainerHeight="unset"
          textContainerHeight1="unset"
        />
        <ContentBox
          titleBadge={false}
          imageBadge={false}
          category={false}
          title="Hendrerit blandit"
          imageUnderTitle={false}
          category="Category"
          text="A aliquam pharetra in nec vitae ultrices commodo placerat eget."
          image={false}
          title
          text
          imageThumb={false}
          author={false}
          icon
          buttons={false}
          titleIcon={false}
          propPosition="absolute"
          propTop="473px"
          propLeft="80px"
          propWidth="145.7px"
          picture="/picture4@2x.png"
          propWidth1="unset"
          propHeight="unset"
          propBorderRadius="unset"
          propBackgroundColor="unset"
          propPadding="unset"
          iconTablerIconsViewfinder="/icon--tablericons--lock.svg"
          propAlignSelf="stretch"
          propAlignSelf1="stretch"
          propMargin="0"
          propFontSize="20px"
          propFontWeight="700"
          propTextAlign="left"
          propFlex="1"
          iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--pencil1.svg"
          picture1="/picture4@2x.png"
          propColor="#475569"
          propTextAlign1="left"
          userThumb="/user-thumb-4@2x.png"
          propLeft1="calc(50% - 47.85px)"
          contentBoxAlignSelf="unset"
          contentBoxFlex="unset"
          categoryAlignSelf="stretch"
          categoryWidth="unset"
          pictureIconAlignSelf="stretch"
          pictureIconOverflow="hidden"
          pictureIconWidth="unset"
          paragraphFontSize="12px"
          userCardAlignSelf="stretch"
          userCardWidth="unset"
          userCardFlexWrap="unset"
          buttonsGroupFlexWrap="unset"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus4.svg"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus5.svg"
          text2
          text2
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-12.svg"
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-13.svg"
          iconRight1
          iconRight1
          iconLeft1={false}
          iconLeft1={false}
          propBackgroundColor2="#2563eb"
          propBackgroundColor2="unset"
          propHeight2="48px"
          propHeight2="48px"
          propFlex2="1"
          propFlex2="1"
          propBorderRadius2="8px"
          propBorderRadius2="8px"
          propBorder1="2px solid #2563eb"
          propBorder1="2px solid #2563eb"
          propPadding2="12px 9px"
          propPadding2="12px 9px"
          propBoxShadow1="unset"
          propBoxShadow1="unset"
          propAlignSelf3="stretch"
          propAlignSelf3="stretch"
          propColor2="#fff"
          propColor2="#2563eb"
          propAlignSelf12="stretch"
          propAlignSelf12="stretch"
          propFontSize2="16px"
          propFontSize2="16px"
          propFontWeight2="500"
          propFontWeight2="500"
          propMargin2="unset"
          propMargin2="unset"
          buttonMinWidth="unset"
          buttonMinWidth1="unset"
          textContainerHeight="unset"
          textContainerHeight1="unset"
        />
        <ContentBox
          titleBadge={false}
          imageBadge={false}
          category={false}
          title="Enim risus turpis"
          imageUnderTitle={false}
          category="Category"
          text="Tristique dui vestibulum senectus ac duis etiam adipiscing sapien."
          image={false}
          title
          text
          imageThumb={false}
          author={false}
          icon
          buttons={false}
          titleIcon={false}
          propPosition="absolute"
          propTop="473px"
          propLeft="273.7px"
          propWidth="145.7px"
          picture="/picture5@2x.png"
          propWidth1="unset"
          propHeight="unset"
          propBorderRadius="unset"
          propBackgroundColor="unset"
          propPadding="unset"
          iconTablerIconsViewfinder="/icon--tablericons--layoutdashboard.svg"
          propAlignSelf="stretch"
          propAlignSelf1="stretch"
          propMargin="0"
          propFontSize="20px"
          propFontWeight="700"
          propTextAlign="left"
          propFlex="1"
          iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--pencil1.svg"
          picture1="/picture5@2x.png"
          propColor="#475569"
          propTextAlign1="left"
          userThumb="/user-thumb-5@2x.png"
          propLeft1="calc(50% - 47.85px)"
          contentBoxAlignSelf="unset"
          contentBoxFlex="unset"
          categoryAlignSelf="stretch"
          categoryWidth="unset"
          pictureIconAlignSelf="stretch"
          pictureIconOverflow="hidden"
          pictureIconWidth="unset"
          paragraphFontSize="12px"
          userCardAlignSelf="stretch"
          userCardWidth="unset"
          userCardFlexWrap="unset"
          buttonsGroupFlexWrap="unset"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus4.svg"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus5.svg"
          text2
          text2
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-12.svg"
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-13.svg"
          iconRight1
          iconRight1
          iconLeft1={false}
          iconLeft1={false}
          propBackgroundColor2="#2563eb"
          propBackgroundColor2="unset"
          propHeight2="48px"
          propHeight2="48px"
          propFlex2="1"
          propFlex2="1"
          propBorderRadius2="8px"
          propBorderRadius2="8px"
          propBorder1="2px solid #2563eb"
          propBorder1="2px solid #2563eb"
          propPadding2="12px 9px"
          propPadding2="12px 9px"
          propBoxShadow1="unset"
          propBoxShadow1="unset"
          propAlignSelf3="stretch"
          propAlignSelf3="stretch"
          propColor2="#fff"
          propColor2="#2563eb"
          propAlignSelf12="stretch"
          propAlignSelf12="stretch"
          propFontSize2="16px"
          propFontSize2="16px"
          propFontWeight2="500"
          propFontWeight2="500"
          propMargin2="unset"
          propMargin2="unset"
          buttonMinWidth="unset"
          buttonMinWidth1="unset"
          textContainerHeight="unset"
          textContainerHeight1="unset"
        />
        <ContentBox
          titleBadge={false}
          imageBadge={false}
          category={false}
          title="Aliquam lorem et"
          imageUnderTitle={false}
          category="Category"
          text="Suspendisse ultrices morbi iaculis sit lorem. Mauris nulla odio est a mi a sed gravida."
          image={false}
          title
          text
          imageThumb={false}
          author={false}
          icon
          buttons={false}
          titleIcon={false}
          propPosition="absolute"
          propTop="473px"
          propLeft="467.3px"
          propWidth="145.7px"
          picture="/picture6@2x.png"
          propWidth1="unset"
          propHeight="unset"
          propBorderRadius="unset"
          propBackgroundColor="unset"
          propPadding="unset"
          iconTablerIconsViewfinder="/icon--tablericons--markdown.svg"
          propAlignSelf="stretch"
          propAlignSelf1="stretch"
          propMargin="0"
          propFontSize="20px"
          propFontWeight="700"
          propTextAlign="left"
          propFlex="1"
          iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--pencil1.svg"
          picture1="/picture6@2x.png"
          propColor="#475569"
          propTextAlign1="left"
          userThumb="/user-thumb-2@2x.png"
          propLeft1="calc(50% - 47.85px)"
          contentBoxAlignSelf="unset"
          contentBoxFlex="unset"
          categoryAlignSelf="stretch"
          categoryWidth="unset"
          pictureIconAlignSelf="stretch"
          pictureIconOverflow="hidden"
          pictureIconWidth="unset"
          paragraphFontSize="12px"
          userCardAlignSelf="stretch"
          userCardWidth="unset"
          userCardFlexWrap="unset"
          buttonsGroupFlexWrap="unset"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus4.svg"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus5.svg"
          text2
          text2
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-12.svg"
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-13.svg"
          iconRight1
          iconRight1
          iconLeft1={false}
          iconLeft1={false}
          propBackgroundColor2="#2563eb"
          propBackgroundColor2="unset"
          propHeight2="48px"
          propHeight2="48px"
          propFlex2="1"
          propFlex2="1"
          propBorderRadius2="8px"
          propBorderRadius2="8px"
          propBorder1="2px solid #2563eb"
          propBorder1="2px solid #2563eb"
          propPadding2="12px 9px"
          propPadding2="12px 9px"
          propBoxShadow1="unset"
          propBoxShadow1="unset"
          propAlignSelf3="stretch"
          propAlignSelf3="stretch"
          propColor2="#fff"
          propColor2="#2563eb"
          propAlignSelf12="stretch"
          propAlignSelf12="stretch"
          propFontSize2="16px"
          propFontSize2="16px"
          propFontWeight2="500"
          propFontWeight2="500"
          propMargin2="unset"
          propMargin2="unset"
          buttonMinWidth="unset"
          buttonMinWidth1="unset"
          textContainerHeight="unset"
          textContainerHeight1="unset"
        />
        <ContentBox
          titleBadge={false}
          imageBadge={false}
          category={false}
          title="Sed aliquam lectus"
          imageUnderTitle={false}
          category="Category"
          text="Rhoncus ut montes quis eget vulputate. Id hac consectetur ornare neque."
          image={false}
          title
          text
          imageThumb={false}
          author={false}
          icon
          buttons={false}
          titleIcon={false}
          propPosition="absolute"
          propTop="737px"
          propLeft="80px"
          propWidth="145.7px"
          picture="/picture4@2x.png"
          propWidth1="unset"
          propHeight="unset"
          propBorderRadius="unset"
          propBackgroundColor="unset"
          propPadding="unset"
          iconTablerIconsViewfinder="/icon--tablericons--pig.svg"
          propAlignSelf="stretch"
          propAlignSelf1="stretch"
          propMargin="0"
          propFontSize="20px"
          propFontWeight="700"
          propTextAlign="left"
          propFlex="1"
          iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--pencil1.svg"
          picture1="/picture4@2x.png"
          propColor="#475569"
          propTextAlign1="left"
          userThumb="/user-thumb-4@2x.png"
          propLeft1="calc(50% - 47.85px)"
          contentBoxAlignSelf="unset"
          contentBoxFlex="unset"
          categoryAlignSelf="stretch"
          categoryWidth="unset"
          pictureIconAlignSelf="stretch"
          pictureIconOverflow="hidden"
          pictureIconWidth="unset"
          paragraphFontSize="12px"
          userCardAlignSelf="stretch"
          userCardWidth="unset"
          userCardFlexWrap="unset"
          buttonsGroupFlexWrap="unset"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus4.svg"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus5.svg"
          text2
          text2
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-12.svg"
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-13.svg"
          iconRight1
          iconRight1
          iconLeft1={false}
          iconLeft1={false}
          propBackgroundColor2="#2563eb"
          propBackgroundColor2="unset"
          propHeight2="48px"
          propHeight2="48px"
          propFlex2="1"
          propFlex2="1"
          propBorderRadius2="8px"
          propBorderRadius2="8px"
          propBorder1="2px solid #2563eb"
          propBorder1="2px solid #2563eb"
          propPadding2="12px 9px"
          propPadding2="12px 9px"
          propBoxShadow1="unset"
          propBoxShadow1="unset"
          propAlignSelf3="stretch"
          propAlignSelf3="stretch"
          propColor2="#fff"
          propColor2="#2563eb"
          propAlignSelf12="stretch"
          propAlignSelf12="stretch"
          propFontSize2="16px"
          propFontSize2="16px"
          propFontWeight2="500"
          propFontWeight2="500"
          propMargin2="unset"
          propMargin2="unset"
          buttonMinWidth="unset"
          buttonMinWidth1="unset"
          textContainerHeight="unset"
          textContainerHeight1="unset"
        />
        <ContentBox
          titleBadge={false}
          imageBadge={false}
          category={false}
          title="Cursus diam"
          imageUnderTitle={false}
          category="Category"
          text="Feugiat consectetur eu commodo odio venenatis pretium libero. Volutpat ultricies nisl turpis id."
          image={false}
          title
          text
          imageThumb={false}
          author={false}
          icon
          buttons={false}
          titleIcon={false}
          propPosition="absolute"
          propTop="737px"
          propLeft="273.7px"
          propWidth="145.7px"
          picture="/picture5@2x.png"
          propWidth1="unset"
          propHeight="unset"
          propBorderRadius="unset"
          propBackgroundColor="unset"
          propPadding="unset"
          iconTablerIconsViewfinder="/icon--tablericons--flag.svg"
          propAlignSelf="stretch"
          propAlignSelf1="stretch"
          propMargin="0"
          propFontSize="20px"
          propFontWeight="700"
          propTextAlign="left"
          propFlex="1"
          iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--pencil1.svg"
          picture1="/picture5@2x.png"
          propColor="#475569"
          propTextAlign1="left"
          userThumb="/user-thumb-5@2x.png"
          propLeft1="calc(50% - 47.85px)"
          contentBoxAlignSelf="unset"
          contentBoxFlex="unset"
          categoryAlignSelf="stretch"
          categoryWidth="unset"
          pictureIconAlignSelf="stretch"
          pictureIconOverflow="hidden"
          pictureIconWidth="unset"
          paragraphFontSize="12px"
          userCardAlignSelf="stretch"
          userCardWidth="unset"
          userCardFlexWrap="unset"
          buttonsGroupFlexWrap="unset"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus4.svg"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus5.svg"
          text2
          text2
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-12.svg"
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-13.svg"
          iconRight1
          iconRight1
          iconLeft1={false}
          iconLeft1={false}
          propBackgroundColor2="#2563eb"
          propBackgroundColor2="unset"
          propHeight2="48px"
          propHeight2="48px"
          propFlex2="1"
          propFlex2="1"
          propBorderRadius2="8px"
          propBorderRadius2="8px"
          propBorder1="2px solid #2563eb"
          propBorder1="2px solid #2563eb"
          propPadding2="12px 9px"
          propPadding2="12px 9px"
          propBoxShadow1="unset"
          propBoxShadow1="unset"
          propAlignSelf3="stretch"
          propAlignSelf3="stretch"
          propColor2="#fff"
          propColor2="#2563eb"
          propAlignSelf12="stretch"
          propAlignSelf12="stretch"
          propFontSize2="16px"
          propFontSize2="16px"
          propFontWeight2="500"
          propFontWeight2="500"
          propMargin2="unset"
          propMargin2="unset"
          buttonMinWidth="unset"
          buttonMinWidth1="unset"
          textContainerHeight="unset"
          textContainerHeight1="unset"
        />
        <ContentBox
          titleBadge
          imageBadge
          category
          title="Facilisi vel malesuada"
          imageUnderTitle
          category="Category"
          text="Nibh cursus ultricies id neque proin urna vivamus bibendum. Quam sit platea integer sit."
          image
          title
          text
          imageThumb
          author
          icon
          buttons
          titleIcon
          picture="/picture6@2x.png"
          iconTablerIconsViewfinder="/icon--tablericons--viewfinder.svg"
          iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--pencil1.svg"
          picture1="/picture6@2x.png"
          userThumb="/user-thumb-2@2x.png"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus4.svg"
          iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus5.svg"
          text2
          text2
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-12.svg"
          iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright-13.svg"
          iconRight1
          iconRight1
          iconLeft1={false}
          iconLeft1
          propBackgroundColor2="#2563eb"
          propHeight2="48px"
          propFlex2="1"
          propBorderRadius2="8px"
          propBorder1="2px solid #2563eb"
          propPadding2="12px 9px"
          propBoxShadow1="unset"
          propAlignSelf3="stretch"
          propColor2="#fff"
          propAlignSelf12="stretch"
          propFontSize2="16px"
          propFontWeight2="500"
          propMargin2="unset"
          buttonMinWidth="unset"
          textContainerHeight="unset"
        />
      </div>
    </footer>
  );
};

export default Features;
